-- CARGA LOS ESTADOS UTILIZADOS PARA LOS USUARIOS Y PROVEEDORES. ESTO SE USA PARA LLENAR LOS SELECT/DROPDOWNLIST
CREATE PROC sp_Cargar_Estados_Usuarios_Proveedores_ddl
AS
BEGIN
	SELECT ID_Estado AS Valor, Descripcion as Texto 
	FROM Estados
	WHERE ID_Estado IN (3, 4)
	ORDER BY Texto ASC
END