-- PROCEDIMIENTO ALMACENADO QUE DEVUELVE LA CANTIDAD DE FACTURAS PENDIENTES DE APLICAR
-- EXEC sp_ConsultaCantidadFacturasPendientes
CREATE PROC sp_ConsultaCantidadFacturasPendientes
AS
BEGIN
	SELECT COUNT(*) AS CANTIDAD
	FROM Facturas
	WHERE Estado = 1
END