-- PROCEDIMIENTO ALMACENADO QUE DEVUELVE LA CANTIDAD DE DOCUMENTOS DE PAGO PENDIENTES DE APLICAR
-- EXEC sp_ConsultaCantidadDocsPagoPendientes
CREATE PROC sp_ConsultaCantidadDocsPagoPendientes
AS
BEGIN
	SELECT COUNT(*) AS CANTIDAD
	FROM Documentos_Formas_Pago
	WHERE Estado = 1
END